[tox]
env_list = py312, lint, typecheck
skip_missing_interpreters = true

[testenv]
runner = uv-venv-lock-runner
groups = dev
commands = pytest {posargs}

[testenv:lint]
commands = ruff check .

[testenv:typecheck]
commands = pyrefly check
